---
- name: (RedHat) deps...
  when: ansible_os_family == "RedHat"
  include: RedHat.yml

- name: (Debian) deps...
  when: ansible_os_family == "Debian"
  include: Debian.yml
  
- name: download tgz...
  get_url: >
    url='{{openresty_mirror}}/{{openresty_tgz}}'
    dest='/tmp/{{openresty_tgz}}'

- name: unarchive...
  unarchive: >
    copy=no
    src=/tmp/{{openresty_tgz}}
    dest='/opt'

- name: configure...
  command: >
    ./configure
    --prefix={{openresty_install_dir}}
    --with-pcre-jit
    --with-ipv6
  args:
    chdir: '/opt/{{openresty_name}}'
    creates: '/opt/{{openresty_name}}/Makefile'

- name: make...
  command: make build
  args:
    chdir: '/opt/{{openresty_name}}'

- name: install...
  command: make install
  args:
    chdir: '/opt/{{openresty_name}}'
    creates: '{{openresty_install_dir}}/nginx/sbin/nginx'

- name: link luajit as lua...
  file: >-
    src={{openresty_install_dir}}/luajit/bin/luajit-2.1.0-beta1
    dest={{openresty_install_dir}}/luajit/bin/lua
    state=link
    
- name: downloading luarocks...
  get_url: >-
    url='{{luarocks_tgz_url}}'
    dest=/tmp/{{luarocks_tgz}}

- name: unarchive luarocks...
  unarchive: copy=no src=/tmp/{{luarocks_tgz}} dest=/opt

- name: configure luarocks...
  command: >
    ./configure
    --prefix={{luajit_dir}}
    --sysconfdir={{luarocks_dir}}
    --with-lua={{luajit_dir}}
    --lua-suffix={{luajit_suffix}}
    --with-lua-include={{luajit_include_dir}}
  args:
    chdir: /opt/{{luarocks_name}}

- name: build luarocks...
  command: make build
  args:
    chdir: /opt/{{luarocks_name}}

- name: install luarocks...
  command: make install
  args:
    chdir: /opt/{{luarocks_name}}

- name: proxify luarocks...
  when: proxy_env.http_proxy is defined
  template: >-
    src=config-5.1.lua.j2
    dest={{luarocks_dir}}/config-5.1.lua
    owner=root
    group=root
    mode=0644

- name: install some rocks..
  command: >
    {{luajit_dir}}/bin/luarocks install {{item}}
  with_items:
    - luasec
    - luajson