---
- name: (RedHat) deps...
  when: ansible_os_family == "RedHat"
  include: RedHat.yml

- name: (Debian) deps...
  when: ansible_os_family == "Debian"
  include: Debian.yml
  
- name: download tgz...
  get_url: >
    url='{{openresty_mirror}}/{{openresty_tgz}}'
    dest='/tmp/{{openresty_tgz}}'
    owner=root
    group=root
    mode=0644

- name: create build dirs
  with_items:
    - '{{openresty_build_dir}}'
    - '{{luarocks_build_dir}}'
  file: >-
    path={{item}}
    state=directory
    owner=root
    group=root
    mode=0755

- name: download nginx-auth-ldap...
  git: >-
    repo=https://github.com/kvspb/nginx-auth-ldap.git
    dest={{openresty_build_dir}}/nginx-auth-ldap
    version={{nginx_auth_ldap_ver}}
    
- name: unarchive openresty...
  unarchive: >
    copy=no
    src=/tmp/{{openresty_tgz}}
    dest={{openresty_build_dir}}
    creates={{openresty_build_dir}}/{{openresty_name}}

- name: configure openresty...
  command: >
    ./configure
    --prefix={{openresty_install_dir}}
    --with-pcre-jit
    --with-ipv6
    --add-module={{openresty_build_dir}}/nginx-auth-ldap
  args:
    chdir: '/{{openresty_build_dir}}/{{openresty_name}}'
    creates: '/{{openresty_build_dir}}/{{openresty_name}}/Makefile'

- name: make build install...
  command: make build install
  args:
    chdir: '/{{openresty_build_dir}}/{{openresty_name}}'
    creates: '{{openresty_install_dir}}/nginx/sbin/nginx'

- name: downloading luarocks...
  get_url: >-
    url={{luarocks_tgz_url}}
    dest=/tmp/{{luarocks_tgz}}
    owner=root
    group=root
    mode=0644

- name: unarchive luarocks...
  unarchive: >
    copy=no
    src=/tmp/{{luarocks_tgz}}
    dest={{luarocks_build_dir}}
    creates={{luarocks_build_dir}}/{{luarocks_name}}

- name: configure luarocks...
  command: >
    ./configure
    --with-lua={{luajit_dir}}
    --lua-suffix=jit
    --with-lua-include={{luajit_include_dir}}
  args:
    chdir: /{{luarocks_build_dir}}/{{luarocks_name}}
    creates: /{{luarocks_build_dir}}/{{luarocks_name}}/config.unix

- name: build and install luarocks...
  command: make build install
  args:
    chdir: /{{luarocks_build_dir}}/{{luarocks_name}}
    creates: /usr/local/bin/luarocks

- name: install some rocks..
  with_items: '{{luarocks_install | default([])}}'
  command: >
    /usr/local/bin/luarocks install {{item}}
  args:
    creates: /usr/local/lib/luarocks/rocks/{{item}}

- name: cleanup...
  when: openresty_cleanup
  with_items:
    - '{{openresty_build_dir}}'
    - '{{luarocks_build_dir}}'
    - '/tmp/{{openresty_tgz}}'
    - '/tmp/{{luarocks_tgz}}'
  file: >-
    path={{item}}
    state=absent

    
