---
- include_role:
    name: andrewrothstein.unarchive-deps
- include_role:
    name: andrewrothstein.gcc-toolbox
- include_role:
    name: andrewrothstein.openssl
  vars:
    openssl_include_dev_pkgs: true
- include_role:
    name: andrewrothstein.git
- include_role:
    name: andrewrothstein.luarocks

- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: install os pkg deps
  become: true
  become_user: root
  package:
    name: '{{ openresty_pkgs }}'
    state: present

- name: downloading {{ openresty_url }}
  become: true
  become_user: root
  get_url:
    url: '{{ openresty_url }}'
    dest: '{{ openresty_tmp_tgz }}'
    mode: 0644
    checksum: '{{ openresty_checksum }}'
    timeout: '{{ openresty_timeout_seconds }}'

- name: mkdir {{ openresty_build_dir }}
  become: true
  become_user: root
  file:
    path: '{{ openresty_build_dir }}'
    state: directory
    mode: '0755'

- name: download nginx-auth-ldap...
  become: true
  become_user: root
  git:
    repo: https://github.com/kvspb/nginx-auth-ldap.git
    dest: '{{ openresty_build_dir }}/nginx-auth-ldap'
    version: '{{ nginx_auth_ldap_ver }}'

- name: unarchive openresty...
  become: true
  become_user: root
  unarchive:
    remote_src: true
    src: '{{ openresty_tmp_tgz }}'
    dest: '{{ openresty_build_dir }}'
    creates: '{{ openresty_build_subdir }}'

- name: configure openresty...
  become: true
  become_user: root
  command: >-
    ./configure
    --prefix={{ openresty_install_dir }}
    --with-pcre-jit
    --with-ipv6
    --add-module={{ openresty_build_dir }}/nginx-auth-ldap
  args:
    chdir: '{{ openresty_build_subdir }}'
    creates: '{{ openresty_build_dir }}/{{ openresty_name }}/Makefile'

- name: make build install...
  become: true
  become_user: root
  command: make build install
  args:
    chdir: '{{ openresty_build_subdir }}'
    creates: '{{ openresty_install_dir }}/nginx/sbin/nginx'

- name: cleanup...
  become: true
  become_user: root
  with_items:
    - '{{ openresty_build_dir }}'
    - '/tmp/{{ openresty_tgz }}'
  file:
    path: '{{ item }}'
    state: absent
