---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.gcc_toolbox
  ansible.builtin.include_role:
    name: andrewrothstein.gcc_toolbox
- name: Installingi andrewrothstein.openssl
  ansible.builtin.include_role:
    name: andrewrothstein.openssl
  vars:
    openssl_include_dev_pkgs: true
- name: Installing andrewrothstein.git
  ansible.builtin.include_role:
    name: andrewrothstein.git
- name: Installing andrewrothstein.luarocks (and luajit)
  ansible.builtin.include_role:
    name: andrewrothstein.luarocks

- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Installing OS pkg deps
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ openresty_pkgs }}'
    state: present

- name: Downloading {{ openresty_url }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ openresty_url }}'
    dest: '{{ openresty_tmp_tgz }}'
    mode: '644'
    checksum: '{{ openresty_checksum }}'
    timeout: '{{ openresty_timeout_seconds }}'

- name: Mkdir {{ openresty_build_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ openresty_build_dir }}'
    state: directory
    mode: '755'

- name: Cloning nginx-auth-ldap with git
  become: true
  become_user: root
  ansible.builtin.git:
    repo: https://github.com/kvspb/nginx-auth-ldap.git
    dest: '{{ openresty_build_dir }}/nginx-auth-ldap'
    version: '{{ nginx_auth_ldap_ver }}'

- name: Unarchive openresty...
  become: true
  become_user: root
  ansible.builtin.unarchive:
    remote_src: true
    src: '{{ openresty_tmp_tgz }}'
    dest: '{{ openresty_build_dir }}'
    creates: '{{ openresty_build_subdir }}'

- name: Configure openresty...
  become: true
  become_user: root
  ansible.builtin.command: >-
    ./configure
    --prefix={{ openresty_install_dir }}
    --with-pcre-jit
    --with-ipv6
    --add-module={{ openresty_build_dir }}/nginx-auth-ldap
  args:
    chdir: '{{ openresty_build_subdir }}'
    creates: '{{ openresty_build_dir }}/{{ openresty_name }}/Makefile'

- name: Make, Build, Install
  become: true
  become_user: root
  ansible.builtin.command: make build install
  args:
    chdir: '{{ openresty_build_subdir }}'
    creates: '{{ openresty_install_dir }}/nginx/sbin/nginx'

- name: Cleanup...
  become: true
  become_user: root
  with_items:
    - '{{ openresty_build_dir }}'
    - '/tmp/{{ openresty_tgz }}'
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
