---
- name: (RedHat) deps...
  when: ansible_os_family == "RedHat"
  include: RedHat.yml

- name: (Debian) deps...
  when: ansible_os_family == "Debian"
  include: Debian.yml
  
- name: download tgz...
  get_url: url='{{openresty_mirror}}/{{openresty_tgz}}' dest='/tmp/{{openresty_tgz}}'

- name: unarchive...
  unarchive: >
    copy=no
    src=/tmp/{{openresty_tgz}}
    dest='/opt'

- name: configure...
  command: >
    ./configure
    --prefix {{openresty_install_dir}}
    --with-pcre-jit
    --with-ipv6
  args:
    chdir: '/opt/{{openresty_name}}'
    creates: '/opt/{{openresty_name}}/Makefile'

- name: make...
  command: make build
  args:
    chdir: '/opt/{{openresty_name}}'

- name: install...
  command: make install
  args:
    chdir: '/opt/{{openresty_name}}'
    creates: '{{openresty_install_dir}}/nginx/sbin/nginx'