---
- name: (RedHat) deps...
  package: name={{item}} state=present
  with_items:
    - wget
    - perl
    - readline-devel
    - pcre-devel
    - openssl-devel
    - openldap-devel
    - gcc
    - make
    