---
- name: andrewrothstein.unarchive-deps
  version: v1.2.4
- name: andrewrothstein.gcc-toolbox
  version: v1.1.9
- name: andrewrothstein.git
  version: v3.2.2
- name: andrewrothstein.luarocks
  version: v1.1.7
- name: andrewrothstein.openssl
  version: v1.0.8
