---
- name: andrewrothstein.unarchive-deps
  version: v1.2.3
- name: andrewrothstein.gcc-toolbox
  version: v1.1.5
- name: andrewrothstein.git
  version: v3.1.6
- name: andrewrothstein.luarocks
  version: v1.1.5
- name: andrewrothstein.openssl
  version: v1.0.8
