---
- name: andrewrothstein.unarchivedeps
  version: 3.0.3
- name: andrewrothstein.gcc_toolbox
  version: 2.1.0
- name: andrewrothstein.git
  version: v3.2.11
- name: andrewrothstein.luarocks
  version: v1.2.1
- name: andrewrothstein.openssl
  version: v1.2.3
